ALTER TABLE pages
    ADD COLUMN whatsapp VARCHAR(36) DEFAULT NULL AFTER cta_link,
    ADD COLUMN map_address VARCHAR(255) DEFAULT NULL AFTER whatsapp;

CREATE TABLE IF NOT EXISTS page_services (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    page_id INT UNSIGNED NOT NULL,
    position TINYINT UNSIGNED NOT NULL DEAFULT 0,
    icon VARCHAR(10) DEFAULT NULL,
    title VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,
    CONSTRAINT fk_page_services_page FOREIGN KEY (page_id) REFERENCES pages(id) ON DELETE CASCADE  
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS page_team_members(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    page_id INT UNSIGNED NOT NULL,
    position TINYINT UNSIGNED NOT NULL DEFAULT 0,
    photo VARCHAR(255) DEFAULT NULL,
    name VARCHAR(150) NOT NULL,
    role VARCHAR(150) DEFAULT NULL,
    whatsapp VARCHAR(30) DEFAULT NULL,
    CONSTRAINT fk_page_team_page FOREIGN KEY (page_id) REFERENCES pages(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;