ALTER TABLE pages
    ADD COLUMN topbar_phone VARCHAR(30) DEFAULT NULL AFTER whatsapp,
    ADD COLUMN topbar_note VARCHAR(160) DEFAULT NULL AFTER topbar_phone,
    ADD COLUMN logo VARCHAR(255) DEFAULT NULL AFTER image,
    ADD COLUMN privacy_notice TEXT DEFAULT NULL AFTER map_address;

CREATE TABLE IF NOT EXISTS page_steps (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    page_id INT UNSIGNED NOT NULL,
    position TINYINT UNSIGNED NOT NULL DEFAULT 0,
    title VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,
    CONSTRAINT fk_page_steps_page FOREIGN KEY (page_id) REFERENCES pages(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;